"""
Paper -> HTML.

Used by the WeasyPrint renderer, and also useful on its own for a print
preview in the frontend. Layout follows a Karnataka State Board question
paper: header block (title, subject, grade, total marks), numbered questions
with per-question marks in the right margin, MCQ options as (a)-(d), then the
answer key on a fresh page.
"""
from __future__ import annotations

from html import escape

_STYLE = """
@page { size: A4; margin: 18mm 16mm 20mm 16mm;
        @bottom-center { content: "Page " counter(page) " of " counter(pages);
                         font-size: 9pt; color: #666; } }
body { font-family: "Noto Sans", "Noto Sans Kannada", "DejaVu Sans", sans-serif;
       font-size: 11pt; line-height: 1.45; color: #111; }
.header { text-align: center; border-bottom: 2px solid #111; padding-bottom: 8px;
          margin-bottom: 14px; }
.header h1 { font-size: 15pt; margin: 0 0 4px; }
.meta { display: flex; justify-content: space-between; font-size: 10pt;
        color: #333; margin-top: 6px; }
.instructions { font-size: 9.5pt; color: #444; margin: 0 0 16px;
                border-left: 3px solid #ccc; padding-left: 8px; }
.q { margin: 0 0 12px; page-break-inside: avoid; }
.q-head { display: flex; gap: 8px; align-items: baseline; }
.q-num { font-weight: 600; min-width: 22px; }
.q-text { flex: 1; }
.q-marks { font-weight: 600; white-space: nowrap; color: #333; }
.options { margin: 4px 0 0 30px; padding: 0; list-style: none; }
.options li { margin: 2px 0; }
.section-break { page-break-before: always; }
.key h2 { font-size: 13pt; border-bottom: 1px solid #111; padding-bottom: 4px; }
.key .a { margin: 0 0 10px 30px; }
.key .a .label { font-weight: 600; }
.key .expl { color: #444; font-size: 10pt; }
.footer-note { margin-top: 18px; font-size: 9pt; color: #777; text-align: center; }
"""

_OPTION_LABELS = "abcdefgh"


def _instructions(paper) -> str:
    """Standard rubric lines, tailored to what's actually in the paper."""
    types = {item.question.type.value for item in paper.items}
    lines = ["All questions are compulsory.", "Marks for each question are shown against it."]
    if "MCQ" in types:
        lines.append("For multiple-choice questions, write the letter of the correct option.")
    if "Long" in types:
        lines.append("Answer long-answer questions in full, showing all steps or points.")
    return "".join(f"<div>{escape(line)}</div>" for line in lines)


def render_paper_html(paper, *, include_answer_key: bool = True) -> str:
    """Build a complete standalone HTML document for a paper."""
    grades = sorted({item.question.grade for item in paper.items})
    grade_label = ", ".join(str(g) for g in grades) if grades else "-"

    parts: list[str] = [
        "<!DOCTYPE html><html><head><meta charset='utf-8'>",
        f"<title>{escape(paper.title)}</title>",
        f"<style>{_STYLE}</style></head><body>",
        "<div class='header'>",
        "<h1>Karnataka State Board</h1>",
        f"<div>{escape(paper.title)}</div>",
        "<div class='meta'>",
        f"<span>Subject: {escape(paper.subject.name)}</span>",
        f"<span>Grade: {escape(grade_label)}</span>",
        f"<span>Maximum Marks: {paper.total_marks}</span>",
        "</div></div>",
        f"<div class='instructions'>{_instructions(paper)}</div>",
    ]

    ordered = sorted(paper.items, key=lambda i: i.order_index)

    for n, item in enumerate(ordered, start=1):
        q = item.question
        parts.append("<div class='q'><div class='q-head'>")
        parts.append(f"<span class='q-num'>{n}.</span>")
        parts.append(f"<span class='q-text'>{escape(q.text)}</span>")
        parts.append(f"<span class='q-marks'>[{item.effective_marks}]</span>")
        parts.append("</div>")
        if q.options:
            parts.append("<ul class='options'>")
            for label, option in zip(_OPTION_LABELS, q.options):
                parts.append(f"<li>({label}) {escape(str(option))}</li>")
            parts.append("</ul>")
        parts.append("</div>")

    if include_answer_key:
        parts.append("<div class='section-break key'><h2>Answer Key</h2>")
        for n, item in enumerate(ordered, start=1):
            q = item.question
            parts.append("<div class='a'>")
            parts.append(
                f"<div><span class='label'>{n}.</span> {escape(q.answer)}</div>"
            )
            if q.explanation:
                parts.append(f"<div class='expl'>{escape(q.explanation)}</div>")
            parts.append("</div>")
        parts.append("</div>")

    parts.append(
        "<div class='footer-note'>Generated by the Question Bank Generator.</div>"
    )
    parts.append("</body></html>")
    return "".join(parts)
